from setuptools import setup

setup(
    name='bermuda3',
    version='6.0.0',
    packages=['core', 'monitor', 'receiver', 'new_admin', 'util', 'cache'],
    py_modules=['new_admind', 'receiverd', 'retryd', 'routerd', 'reportd', 'agentd', 'monitord', 'emaild',
                'error_maild', 'timerd', 'retry_beated', 'celeryconfig', 'refresh_countd', 'sync_rcmsd',
                'sync_portald', 'sync_all_rcmsd', 'alarm_emaild', 'check_errord', 'sync_portal_by_queued', "device_typed",
                'postal_rd', 'edge_not_200_alarmd', 'subcenter_resultd', 'celery_monitord', 'failed_device_emaild',
                'update_redis_channel_customerd', 'preload_url_timer_redis_handled', 'check_url_autodeskd', 'autodesk_failed_emaild',
                'preload_url_timer_pulld', 'refresh_failed_emaild', 'refresh_last_hpcc_emaild', 'failed_url_processd',
                'webluker_username_url_upd', 'refresh_resultd', 'gunicorn_config', 'receiverd_g', 'refresh_preload_updated',
                'count_devicesd','staticsitc_preload_urld','count_device_status_preload_alld','subcenter_countd','cert_update_dayd'],
    scripts=['bin/startup.sh', 'bin/emaild.sh', 'bin/router.sh', 'bin/retry.sh', 'bin/report.sh', 'bin/timer.sh',
             'bin/error_mail.sh', 'bin/sync_redis.sh', 'bin/device_type.sh', 'bin/postal_r.sh', 'bin/edge_not_200_alarm.sh',
             'bin/subcenter_result.sh', 'bin/update_redis_channel_customer.sh', 'bin/preload_url_timer_redis_handle.sh',
             'bin/check_url_autodesk.sh', 'bin/autodesk_failed_email.sh', 'bin/preload_url_timer_pull.sh',
             'bin/refresh_failed_email.sh', 'bin/refresh_last_hpcc_email.sh', 'bin/failed_url_process.sh',
             'bin/webluker_username_url_up.sh', 'bin/refresh_result.sh', 'bin/refresh_preload.sh','bin/count_devices.sh',
             'bin/staticsitc_preload_url.sh','bin/count_device_status_preload_all.sh','bin/subcenter_count.sh','bin/cert_update_day.sh'],
    entry_points={
        'console_scripts': [
            'new_admind=new_admind:main',
            'receiverd=receiverd:main',
            'retryd=retryd:main',
            'routerd=routerd:main',
            'refresh_resultd=refresh_resultd:main',
            'reportd=reportd:main',
            'agentd=agentd:main',
            'monitord=monitord:main',
            'emaild=emaild:main',
            'error_maild=error_maild:main',
            'timerd=timerd:main',
            'retry_beated=retry_beated:main',
            'error_eamild=error_eamild:main',
            'refresh_countd=refresh_countd:main',
            'sync_rcmsd=sync_rcmsd:main',
            'sync_portald=sync_portald:main',
            'device_typed=device_typed:main',
            'sync_portal_by_queued=sync_portal_by_queued:main',
            'sync_all_rcmsd=sync_all_rcmsd:main',
            'check_errord=check_errord:main',
            'alarm_emaild=alarm_emaild:main',
            'postal_rd=postal_rd:main',
            'edge_not_200_alarmd=edge_not_200_alarmd:main',
            'subcenter_resultd=subcenter_resultd:main',
            'celery_monitord=celery_monitord:main',
            'failed_device_emaild=failed_device_emaild:main',
            'update_redis_channel_customerd=update_redis_channel_customerd:main',
            'check_url_autodeskd=check_url_autodeskd:main',
            'autodesk_failed_emaild=autodesk_failed_emaild:main',
            'preload_url_timer_redis_handled=preload_url_timer_redis_handled:main',
            'preload_url_timer_pulld=preload_url_timer_pulld:main',
            'refresh_failed_emaild=refresh_failed_emaild:main',
            'refresh_last_hpcc_emaild=refresh_last_hpcc_emaild:main',
            'failed_url_processd=failed_url_processd:main',
            'webluker_username_url_upd=webluker_username_url_upd:main',
            'refresh_preload_updated=refresh_preload_updated:main',
            'count_devicesd=count_devicesd:main',
            'staticsitc_preload_urld=staticsitc_preload_urld:main',
            'count_device_status_preload_alld=count_device_status_preload_alld:main',
            'subcenter_countd=subcenter_countd:main',
            'cert_update_dayd=cert_update_dayd:main'

        ]
    },
    include_package_data=True,
    zip_safe=False,
    install_requires=[

        'simplejson==3.16.0',
        'celery==4.2.0',
        'httplib2==0.19.0',
        'redis==2.10.6',
        'flask==1.0.2',
        'flask_principal==0.4.0',
        'flask_login==0.4.1',
        'flup==1.0.3',
        'pymongo==3.7.1',
        # 'paramiko==1.15.2',
        'pika==0.12.0',
        'eventlet==0.24.0',
        'gevent==1.3.5',
        'requests==2.19.1',
        'python-etcd==0.4.5',
        'nose==1.3.7',
        'pyOpenSSL==18.0.0',
        'pycrypto==2.6.1',
        'gunicorn==19.9.0',
        'aiohttp==3.4.4'

    ]
)
