#-*- coding:utf-8 -*-
"""
Created on 2011-5-25

@author: wenwen
"""

STATUS_UNPROCESSED = 0
STATUS_SUCCESS = 200
STATUS_EP80_DOWN = 203
STATUS_NOT_OPEN = 204
STATUS_REPEAT = 205
STATUS_INVALID_URL = 400
STATUS_RESOLVE_FAILED = 500
STATUS_CONNECT_FAILED = 503
STATUS_RETRY_SUCCESS = 206
STATUS_TIMEOUT = 504

URL_OVERLOAD_PER_HOUR = 10000
DIR_OVERLOAD_PER_HOUR = 100

#PRELOAD
PRELOAD_STATUS_SUCCESS = 200
PRELOAD_STATUS_REPEAT = 204
PRELOAD_STATUS_REPEATED = 205
PRELOAD_STATUS_RETRYED = 206
PRELOAD_STATUS_FAILED = 500
PRELOAD_STATUS_TIMEOUT = 208
# md5 different
PRELOAD_STATUS_MD5_DIFF = 406

PRELOAD_URL_OVERLOAD_PER_HOUR = 10000
# script processing pre loading device status without reporting info,set value 504
PRELOAD_STATUS_NOT_REPORT = 504


##NTEST
NTESE_ADDRESS = 'http://cacheadmin.x.netease.com:8082/cdnreport/'
NTESE_DOMAIN = 'cacheadmin.x.netease.com'
NTEST_PORT = '8082'
PASSWORD_NTESE = 'q9qvr2@nl$'
USERNAME_NTESE = 'cdnuser'


#monitor
MONITOR_DEVICE_STATUS = [STATUS_SUCCESS, STATUS_NOT_OPEN,STATUS_CONNECT_FAILED]
MONITOR_DEVICE_STATUS_FAILED = [STATUS_NOT_OPEN,STATUS_CONNECT_FAILED]
MONITOR_DEVICE_STATUS_EMAIL = [STATUS_CONNECT_FAILED]

